const enum TokenKindEnum {
	EOF = "EOF",
	NotFinished = "not-finished",

	Identifier = "identifier",
	StringLiteral = "string-literal",
	BooleanLiteral = "boolean-literal",
	NumberLiteral = "number-literal",
	NilLiteral = "nil-literal",

	OpenBrace = "open-brace",
	CloseBrace = "close-brace",
	OpenSquare = "open-square",
	CloseSquare = "close-square",
	SquiglyOpen = "squigly-open",
	SquiglyClose = "squigly-close",

	Addition = "addition",
	Subtract = "subtract",
	Multiply = "multiply",
	Division = "division",
	FloorDivision = "floor-division",
	Modulo = "modulo",
	Exponent = "exponent",
	Concat = "concat",
	Hash = "hash",

	BitAnd = "bit-and",
	BitOr = "bit-or",
	BitXOrNot = "bit-xor-not",
	BitShiftLeft = "bit-shift-left",
	BitShiftRight = "bit-shift-right",

	Equals = "equals",
	NotEquals = "not-equals",
	LessThan = "less-than",
	LessThanEquals = "less-than-equals",
	GreaterThan = "greater-than",
	GreaterThanEquals = "greater-than-equals",
	And = "and",
	Or = "or",
	Not = "not",

	Assign = "assign",
	Semicolon = "semicolon",
	Comma = "comma",
	Dot = "dot",

	FunctionLike = "function",
	If = "if",
	While = "while",
	For = "for",
	Repeat = "repeat",
	In = "in",
	Do = "do",
	Then = "then",
	ElseIf = "elseif",
	Else = "else",
	Until = "until",
	End = "end",
	Return = "return",
	Break = "break",
	Local = "local",
}

export { TokenKindEnum };
